name: find files modified
description: find all files modified

inputs:
  target:
    description: target sha or branch or tag use to compare on origin
    required: false
    default: ''
  origin:
    description: origin sha or branch or tag to compare
    required: false
    default: ''
  parent:
    description: only parent
    required: false
    default: 'false'
  includes:
    description: "filter format start=<starter> end=<end> contains=<contains>"
    default: ''
    required: false
  excludes:
    description: "filter format start=<starter> end=<end> contains=<contains>"
    default: ''
    required: false


outputs:
  files:
    value: ${{ steps.excludes.outputs.value }}
    description: all files modify
  parents:
    value: ${{ steps.parents.outputs.path }}
    description: all parents files modify
  current:
    value: ${{ steps.parents.outputs.origin }}
    description: is current folder modify

runs:
  using: composite
  steps:
    - name: get branch
      id: branch
      uses: pmeig/github-actions/actions/github/branch@main
    - name: find files
      id: files
      shell: bash
      if: ${{ github.event.pull_request.merged == false }}
      run: |
        files=''
        from='${{ inputs.origin }}'
        to='${{ inputs.target }}'
        if [ -z "$from" ]
        then
          from='${{ steps.branch.outputs.current }}'
        fi
        if [ -z "$to" ]
        then
          to='${{ steps.branch.outputs.target }}'
        fi
        compare=$(curl -L -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ github.token }}" -H \
        "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/compare/$to...$from )
        for name in $(echo "$compare" | jq -r '.files[].filename')
        do
          files="$name $files"
        done
        echo "path=$(echo $files)" >> $GITHUB_OUTPUT
    - name: find files pull request
      id: pull-request-files
      shell: bash
      if: ${{ github.event.pull_request.merged == true }}
      run: |
        diff=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files.[].path')
        files=''
        for name in $diff
        do
          files="$name $files"
        done
         echo "path=$(echo $files)" >> $GITHUB_OUTPUT
    - name: apply includes
      id: includes
      uses: pmeig/github-actions/actions/github/diff/filter@main
      with:
        files: ${{ steps.files.outputs.path }}${{ steps.pull-request-files.outputs.path }}
        filter: ${{ inputs.includes }}
    - name: apply excludes
      id: excludes
      uses: pmeig/github-actions/actions/github/diff/filter@main
      with:
        files: ${{ steps.includes.outputs.value }}
        filter: ${{ inputs.excludes }}
        accept: false
    - name: find parent files
      if: ${{ inputs.parent == 'true' }}
      id: parents
      shell: bash
      run: |
        parents=' '
        origin='false'
        for name in $(echo "${{ steps.excludes.outputs.value }}")
        do
          if [[ "$name" == *"/"* ]]
          then
            parent=$(echo "$name" | cut -d'/' -f1)
            if [ "$parent" == 'src' ]
            then
              origin=true
            else
              if [ "$parent" != ".github" ] && [[ "$parents" != *" $parent "* ]]
              then
                parents="$parents$parent "
              fi
            fi
          else
            origin=true
          fi
        done
        parents=$(echo $parents)
        echo "path=$parents" >> $GITHUB_OUTPUT
        echo "origin=$origin" >> $GITHUB_OUTPUT
    - name: clean diff
      shell: bash
      run: |
        rm -rf tmp
