name: read pom
description: read in pom.xml with evaluate


inputs:
  expression:
    required: true
    description: expression do you want read like project.artifactId
  module:
    required: false
    description: module do you want apply expression
    default: ''
  workspace:
    required: false
    default: '.'
    description: localization of your pom


outputs:
  value:
    description: the value of expression do you want extract
    value: ${{ steps.command.outputs.value }}

runs:
  using: composite
  steps:
    - name: execute command for ${{ inputs.expression }}
      id: command
      shell: bash
      working-directory: ${{ inputs.workspace }}
      run: |
        options=''
        if [ -n '${{ inputs.module }}' ]
        then
          options='-pl :${{ inputs.module }}'
        fi
        result=$(mvn help:evaluate $options '-Dexpression=${{ inputs.expression }}' -q -DforceStdout)
        echo "value=$result" >> $GITHUB_OUTPUT