name: configuration pom Sonatype
description: configure your pom to use Sonatype

runs:
  using: composite
  steps:
    - name: plugins
      uses: pmeig/github-actions/actions/java/maven/sonatype/pom/plugins@main
    - name: versions
      uses: pmeig/github-actions/actions/java/maven/sonatype/pom/plugins/version@main