name: setup java
description: install java and prepare cache and settings

inputs:
  branch:
    required: false
    description: branch name use to cache repository
    default: ''
  java:
    required: false
    default: '26'
    description: java version
  artifactory-user:
    required: false
    default: ''
    description: user artifactory
  artifactory-password:
    required: false
    default: ''
    description: artifactory password
  artifactory-url:
    required: false
    default: 'http://jfrog'
    description: artifactory url do you want to connect

runs:
  using: composite
  steps:
    - name: setup maven
      shell: bash
      run: |
        if ! command -v mvn &> /dev/null
        then
          sudo apt-get install -y maven
        fi
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java }}
        distribution: 'temurin'
        cache: maven
    - name: add configuration maven to create server to deploy
      uses: pmeig/github-actions/actions/java/setup/settings@main
      if: ${{ inputs.artifactory-user != '' && inputs.artifactory-password != '' }}
      with:
        artifactory-user: ${{ inputs.artifactory-user }}
        artifactory-password: ${{ inputs.artifactory-password }}
        artifactory-url: ${{ inputs.artifactory-url }}
