name: setup node
description: prepare setup to node

inputs:
  version:
    default: '22'
    description: version node do you want to setup
    required: false
  branch:
    required: true
    description: ''


  artifactory-user:
    description: user use to connect at jfrog
    required: false
    default: ""
  artifactory-password:
    description: password use to connect at jfrog
    required: false
    default: ""
  artifactory-url:
    required: false
    default: 'http://jfrog:8081'
    description: artifactory url do you want to connect
  remote-token:
    description: token use to connect at remote
    required: false
    default: ''
  workspace:
    default: '.'
    required: false
    description: location of node_modules

runs:
  using: composite
  steps:
    - uses: pmeig/github-actions/actions/node/manager@main
      id: manager
    - uses: actions/setup-node@v4
      id: setup-node-version
      with:
        node-version: ${{ inputs.version }}
    - name: Install pnpm
      if: ${{ steps.manager.outputs.value == 'pnpm' }}
      uses: pnpm/action-setup@v4
    - name: Install pnpm
      if: ${{ steps.manager.outputs.value == 'yarn' }}
      shell: bash
      run: |
        npm i -g yarn
    - name: remote
      shell: bash
      if: ${{ inputs.remote-user != '' && inputs.remote-password != '' }}
      run: |
        ${{ steps.manager.outputs.value }} config set registry=https://registry.npmjs.org/
        echo "//registry.npmjs.org/:_authToken=${{ inputs.remote-token }}" >> ~/.npmrc
    - shell: bash
      name: artifactory settings
      if: ${{ inputs.artifactory-user != '' && inputs.artifactory-password != '' }}
      run: |
        export AUTH=$(echo -n ${{ inputs.artifactory-user }}:${{ inputs.artifactory-password }} | base64 -w0)
        echo "NODE_AUTH_TOKEN=$AUTH" >> $GITHUB_ENV
        ${{ steps.manager.outputs.value }} config set @pmeig:registry=${{ inputs.artifactory-url }}/artifactory/
        {
          echo //${{ inputs.artifactory-url }}/artifactory/npm-snapshots-local:_auth=${AUTH}
          echo //${{ inputs.artifactory-url }}/artifactory/npm-releases-local:_auth=${AUTH}
          echo //${{ inputs.artifactory-url }}/artifactory/node:_auth=${AUTH}
        } >> ~/.npmrc

    - name: cache node_modules
      uses: actions/cache@v4
      with:
        key: ${{ steps.manager.outputs.value }}-${{ inputs.branch }}
        path: ${{ inputs.workspace }}/node_modules
